default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: bhagath
  password: reddy

development:
  <<: *default
  database: angpipl_development

test:
  <<: *default
  database: angpipl_test